### ISSUE TITLE
TN: Platform Update for README.md

### ISSUE THREAD

**Issue by inertia186** [steemit/tinman#104]
*As a community member, I would like to know exactly which setup commands I will need, so that I can create a completely new testnet.*

The `README.md` file contains almost everything anyone would need when setting up a new custom testnet.  But it does have a missing package: `git`.  It's also linux specific.

We reference `git submodule` which is no longer required because `simple_steem_client` has been vendored.  See: https://github.com/steemit/tinman/pull/58 

It would also be nice if we had quick setup instructions for macOS.

Anyone on Windows 10 should reevaluate their life choices and consider the Windows Subsystem for Linux.  See: [How to install Ubuntu on Windows 10](https://steemit.com/tutorial/@bitcoinparadise/how-to-install-ubuntu-on-windows-10)

**AC**

- [x] Add `git` to `apt-get`
- [x] Remove `git submodule`
- [x] Add macOS setup instructions
- [x] "Example usage" section has an actual example instead of a stub.

**Comment by bobinson** [comment]
The README should have clear steps. I got this working running virtualenv, pipenv in near random order. 

pip install ijson ---> this is missing from Pipfile and had to install manually.

IMHO it will be great if we can have a clean installation process which use Pipfile and Pipenv than using the current model.

**Comment by relativityboy** [comment]
@bobinson about ijson.. [it's already in the Pipfile](https://github.com/steemit/tinman/blob/develop/Pipfile#L10). I had to install it manually as well on a 'dirty' machine. 

Now that you know it's already in the pip, any thoughts on what caused the issue? I'd love to streamline as you said.

**Comment by bobinson** [comment]
@relativityboy - I will test again in a clean machine. The following is roughly the workflow I am going test. Any deviations I will update ASAP via #145 

- pyenv
- pyenv install 3.6.5
- pyenv global 3.6.5
- pip install pipenv
- get the tinman code
- pipenv check ; pipenv install
