### ISSUE TITLE
Tinman having difficulty creating accounts

### ISSUE THREAD

**Issue by relativityboy** [steemit/tinman#116]
In the Steemworks sandbox, the current master of tinman appears to be having trouble creating accounts. 

**AC**
- [x] figure it out & fix it!

**Comment by inertia186** [comment]
I locally reverted https://github.com/steemit/tinman/commit/dd7f0c0cbc284eaa3dd527372ba07c57b7ece998, and it can create accounts again.  So nievely doubling the money supply to address #109 appears to be an incorrect approach.
