### ISSUE TITLE
Change wait_for_blocks to debug_generate_blocks

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/tinman#12]
So far we've been using `debug_generate_blocks` whenever `wait_blocks` is encountered as an action.  Now that we want to actually sometimes wait for a new block, let's redefine `wait_blocks` to mean waiting for someone else to produce, and `debug_generate_blocks` means we produce.

**Comment by relativityboy** [comment]
Poor context, documentation, no AC. Likely meaningless at this point.
