### ISSUE TITLE
TN: Cannot bootstrap testnet as of HF20

### ISSUE THREAD

**Issue by inertia186** [steemit/tinman#125]
**Original scenario:** If the testnet bootstraps in HF19, the blockchain will activate HF20 when the time arrives.

**Defect scenario:** If the HF20 time has already passed and the bootstrap blockchain *starts* in HF20, tinman can no longer create accounts from the snapshot. 

The HF19 approach was to apply the balance through `account.fee`, which is no longer compatible with HF20, due to how [steem_evaluator.cpp](https://github.com/steemit/steem/blob/c6b865b6f27999cba38f3840151c8306f14f3371/libraries/chain/steem_evaluator.cpp#L332) validates the fee [so that overpayment is not accidently burned](https://github.com/steemit/steem/pull/2561#issuecomment-401908891):

`Must pay the exact account creation fee.`

Even if we hard-coded the fee as an argument to tinman, we still want each account to have a proportonal balance to mainnet.  We need a new solution to bootstrap vesting.

**Temporary Workaround:** Keep adjusting [`STEEM_HARDFORK_0_20_TIME`](https://github.com/steemit/steem/blob/bd1be2f792deb876fdfe292622f7cc1cd88a42ba/libraries/protocol/hardfork.d/0_20.hf#L5) so that it's in the future for each bootstrap.

**AC**

- [x] tinman account creation fixed
- [x] accounts bootstrapped in HF20 still have about the same balance as they did in HF19

**Comment by relativityboy** [comment]
`STEEM_HARDFORK_0_20_TIME` should be calculated unless passed in if at all possible. This may require some testnet specific code in steemd... Perhaps a pure bootstrap mode that fiats blockchain state.
