### ISSUE TITLE
TN: Gatling - Support price feeds

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/tinman#13]
Price feeds must either be ported from the main network #2, or set to a constant value.  Even if price feeds are set to a constant value, the witnesses will need to periodically refresh price feeds since they expire.  Since price feeds require transactions to be issued during the ongoing life of the network, we can't implement a constant-valued feed by simply adding the feed value to the testnet initialization.

**AC**
- [ ] `# Results` comment with details of how to set price-feeds on a TN and a link to/from the execution story.

**Comment by inertia186** [comment]
Looks like this might come in handy after all:

https://github.com/steemit/tinman/issues/92#issuecomment-416001289

> ... perhaps with a configurable constant of **proportionality** ...

*Emphasis mine*

**Comment by relativityboy** [comment]
We've decided to make this story a spike, to iron out what the **AC** should actually be.

**Comment by inertia186** [comment]
As mentioned, one option is to use mainnet as the source of the price feeds, replacing the price with a proportional price and the witness with a testnet witness.  Say we just run `tinman gatling -o -` with the following config:

```json
{
 "transaction_signer" : "tnman",

 "transaction_source" :
 {
  "node" : "https://api.steemit.com",
  "appbase" : "True"
 },

 "min_block_number" : "0",
 "max_block_number" : "0",

 "ported_operations" :
 [
  {"type":"feed_publish_operation","roles":["active"]}
 ]
}
```

What we're saying here is, just port `feed_publish_operation`.  The results I get are:

```json
["submit_transaction",{"esc":"z","tx":{"operations":[{"type":"feed_publish_operation","value":{"exchange_rate":{"base":{"amount":"1023","nai":"@@000000013","precision":3},"quote":{"amount":"1000","nai":"@@000000021","precision":3}},"publisher":"jrswab"}}],"wif_sigs":["zprivatekey:active-tnmanz"]}}]
["submit_transaction",{"esc":"j","tx":{"operations":[{"type":"feed_publish_operation","value":{"exchange_rate":{"base":{"amount":"1023","nai":"@@000000013","precision":3},"quote":{"amount":"1000","nai":"@@000000021","precision":3}},"publisher":"steempress"}}],"wif_sigs":["jprivatekey:active-tnmanj"]}}]
["submit_transaction",{"esc":"j","tx":{"operations":[{"type":"feed_publish_operation","value":{"exchange_rate":{"base":{"amount":"1021","nai":"@@000000013","precision":3},"quote":{"amount":"1000","nai":"@@000000021","precision":3}},"publisher":"blockbrothers"}}],"wif_sigs":["jprivatekey:active-tnmanj"]}}]
["submit_transaction",{"esc":"j","tx":{"operations":[{"type":"feed_publish_operation","value":{"exchange_rate":{"base":{"amount":"1023","nai":"@@000000013","precision":3},"quote":{"amount":"1000","nai":"@@000000021","precision":3}},"publisher":"windforce"}}],"wif_sigs":["jprivatekey:active-tnmanj"]}}]
["submit_transaction",{"esc":"j","tx":{"operations":[{"type":"feed_publish_operation","value":{"exchange_rate":{"base":{"amount":"1026","nai":"@@000000013","precision":3},"quote":{"amount":"1000","nai":"@@000000021","precision":3}},"publisher":"thecryptodrive"}}],"wif_sigs":["jprivatekey:active-tnmanj"]}}]
```

If we were to pipe these results through `tinman amountsub --floor-satoshi 1 --ratio -0.187`, we would get:

```json
["submit_transaction", {"esc": "z", "tx": {"operations": [{"type": "feed_publish_operation", "value": {"exchange_rate": {"base": {"amount": "191", "nai": "@@000000013", "precision": 3}, "quote": {"amount": "187", "nai": "@@000000021", "precision": 3}}, "publisher": "jrswab"}}], "wif_sigs": ["zprivatekey:active-tnmanz"]}}]
["submit_transaction", {"esc": "j", "tx": {"operations": [{"type": "feed_publish_operation", "value": {"exchange_rate": {"base": {"amount": "191", "nai": "@@000000013", "precision": 3}, "quote": {"amount": "187", "nai": "@@000000021", "precision": 3}}, "publisher": "steempress"}}], "wif_sigs": ["jprivatekey:active-tnmanj"]}}]
["submit_transaction", {"esc": "j", "tx": {"operations": [{"type": "feed_publish_operation", "value": {"exchange_rate": {"base": {"amount": "190", "nai": "@@000000013", "precision": 3}, "quote": {"amount": "187", "nai": "@@000000021", "precision": 3}}, "publisher": "blockbrothers"}}], "wif_sigs": ["jprivatekey:active-tnmanj"]}}]
["submit_transaction", {"esc": "j", "tx": {"operations": [{"type": "feed_publish_operation", "value": {"exchange_rate": {"base": {"amount": "191", "nai": "@@000000013", "precision": 3}, "quote": {"amount": "187", "nai": "@@000000021", "precision": 3}}, "publisher": "windforce"}}], "wif_sigs": ["jprivatekey:active-tnmanj"]}}]
["submit_transaction", {"esc": "j", "tx": {"operations": [{"type": "feed_publish_operation", "value": {"exchange_rate": {"base": {"amount": "191", "nai": "@@000000013", "precision": 3}, "quote": {"amount": "187", "nai": "@@000000021", "precision": 3}}, "publisher": "thecryptodrive"}}], "wif_sigs": ["jprivatekey:active-tnmanj"]}}]
```

Next, we need a way to re-write the which witness.  For this, I think `gatling` could be enhanced.  We could add a `replace_witness` option to `ported_operations` of the `.conf`, such as:

```json
{
 "ported_operations" :
 [
  {"type":"feed_publish_operation","roles":["active"],"replace_witness":true}
 ]
}
```

Or something similar.  When `gatling` sees an operation that has this option set to true, it will look at a list of witnesses (also in `.conf`) to pick randomly.

**Comment by relativityboy** [comment]
We want to be able to disconnect Testnet from Mainnet. Having Gatling pipe from Mainnet is interesting and *perhaps* an option to support, but we must also support an artificial price feed that can run "in a vacuum"

**Comment by relativityboy** [comment]
Why an `. actions` file specifically?

Is your thought to wrap submit in a wrapper that loops with a configurable sleep & authentication?

**Comment by inertia186** [comment]
Correct.

**Comment by relativityboy** [comment]
# Results

For MVP on price feed, we'll create a module that can be invoked on it's own, or as a flag within gatling.

There is an assumption made that a valid signing key for all accounts will be provided to the price feed as needed.

The behavior will be customizable in the following ways.
1. Price feed "interval" will be a param or configuration
1. The actions file location will be a param or configuration, but will have a default location, and default file that can be used
1. there will be a param or configuration to use actions file accounts as-stated, or to cycle through existing witnesses.
