### ISSUE TITLE
TN: Bootstrap Initial State

### ISSUE THREAD

**Issue by inertia186** [steemit/tinman#143]
*As a witness verifying things like automatic actions and virtual operations, I want the testnet to bootstrap with transactions in the past, so that I can verify the outcome of these operations without having to wait and hope the testnet stays up for 30 days.*

**AC**

- [ ] can bootstrap with a sample "backfill" of actions that happpen in the past
  - [ ] `gatling` needs to have two new arguments: `--from_blocks_ago` and `--to_blocks_ago` to create `backfill.actions` relative to mainnet head block number.
  - [ ] create new module called `prefixsub` for replacing mainnet public key prefixes with testnet prefixes
  - [ ] actions reside in a `backfill.actions` file that will be injected during `txgen`, if present
    - [ ] define new conf key: `backfill_file`, defaults to: `backfill.actions`
    - [ ] check if `backfill_file` exists and inject the actions right before `update_witnesses` phase
  - [ ] `txgen` will automatically account for additional transactions from `backfill.actions`, if present
    - [ ] define new key: `metadata["backfill_actions:count"]`
    - [ ] add to: `metadata["actions:count"]`

**Comment by bobinson** [comment]
- we can make tinman generate transactions forcing the blockchain to perform various operations ?

**Comment by relativityboy** [comment]
Suggested **AC**
Put all the following in `# Results` comment:
- [ ] define format for actions that happen in the past
- [ ] define where these actions can reside 
    *  update & rename of account creation file?
    * new file?
    * `.actions` file?
    * other?
- [ ] define if format can rezide in txgen created actions file.
- [ ] define which tinman component (ex: `submit`) runs the actions
- [ ] does format define if actions can happen in the future? Why?
- [ ] what kind of time-definitions are supported. And their interactions. 
Possibles include 
    * absolute time (epoch), 
    * relative to a specific time elsewhere defined in the file. 
    * Relative to boot time of tinman component
    * relative to CL parameter abs time
    * relative to approximate switchover to regular block production

**Comment by inertia186** [comment]
So I've come up with an idea called `backfill.actions`.  In a nutshell, we run `gatling` but only enable certain operation types.  The types being disabled are ones that are either too frequent (`custom_json_operation`), interfere with fastgen (`account_witness_vote_operation`), or are present from 1 month ago but no longer part of HF20 (`account_create_with_delegation_operation`).

The purpose of capturing backfill actions is to get as many realistic operations as possible into the fastgen phase.  In order to do this, `initminer` must be the only witness.  So we have get the backfill actions into the blockchain before `init-0:20` are enabled.

I envision it working something like this:

```bash
tinman gatling --from_blocks_ago 864000 --to_blocks_ago 0 | \
  tinman prefixsub > backfill.actions
tinman txgen --backfill backfill.actions
```

The `prefixsub` module will replace any public key with the `STM` prefix to `TST`.  The `txgen` phase will build actions for `account_create_operation`, `transfer_to_vesting_operation`, and `account_update_operation`, then immediately load the backfill actions, followed by enabling `init-0:20` like it does now.

This leaves us with ops like `limit_order_create_operation` that we would like to get into the blockchain during fasgen so that they exist up to 30 days old right when the testnet goes live.

* Disabled:
  * `account_create_with_delegation_operation` - might exist 864000 blocks ago, so just skip them
  * `account_witness_proxy_operation` - pointless because witnesses won't be enabled in fastgen
  * `account_witness_vote_operation` - pointless because witnesses won't be enabled in fastgen
  * `change_recovery_account_operation` - revisit later
  * `claim_reward_balance_operation` - too frequent, no related virtual op
  * `comment_operation` - too frequent, already has testnet logic to speed up testing so no point adding them in fastgen
  * `comment_options_operation` - pointless because comments aren't captured in backfill
  * `delete_comment_operation` - pointless because comments aren't captured in backfill
  * `custom_json_operation` - too frequent, no related virtual op
  * `escrow_approve_operation` - revisit later
  * `escrow_dispute_operation` - revisit later
  * `escrow_release_operation` - revisit later
  * `escrow_transfer_operation` - revisit later
  * `recover_account_operation` - revisit later
  * `request_account_recovery_operation` - revisit later
  * `set_reset_account_operation` - revisit later
  * `vote_operation` - pointless because comments aren't captured in backfill
  * `witness_update_operation` - pointless because witnesses won't be enabled in fastgen
  * `price_operation` - pointless because witnesses won't be enabled in fastgen
  * `feed_publish_operation` - pointless because witnesses won't be enabled in fastgen
* Enabled:
  * `withdraw_vesting_operation` - perfect for backfill
  * `account_create_operation` - couldn't hurt
  * `account_update_operation` - couldn't hurt
  * `cancel_transfer_from_savings_operation` - couldn't hurt
  * `convert_operation` - perfect for backfill
  * `delegate_vesting_shares_operation` - couldn't hurt
  * `limit_order_cancel_operation` - couldn't hurt
  * `limit_order_create2_operation` - perfect for backfill
  * `limit_order_create_operation` - perfect for backfill
  * `set_withdraw_vesting_route_operation` - perfect for backfill
  * `transfer_from_savings_operation` - perfect for backfill
  * `transfer_operation` - couldn't hurt
  * `transfer_to_savings_operation` - couldn't hurt
  * `transfer_to_vesting_operation` - couldn't hurt

**Comment by inertia186** [comment]
# Result

Main **AC** updated.

> * define format for actions that happen in the past
> * [ ]  define where these actions can reside
>   * update & rename of account creation file?
>   * new file?
>   * `.actions` file?
>   * other?

We will use a new file called `backfill.actions`.

> * [ ]  define if format can reside in txgen created actions file.

The `backfill.actions` will be injected right before `txgen.update_witnesses`.  This is required because the backfill must execute in fastgen.  Activating non-initminer witnesses disables fastgen.

> * [ ]  define which tinman component (ex: `submit`) runs the actions

No changes to `submit` are required (although, I do want to move the automatic `wait_blocks` to fix an off-by-one bug).

> * [ ]  does format define if actions can happen in the future? Why?

No.  Fastgen is required because we're trying to reply 30 days worth of actions (~864,000 blocks).

> * [ ]  what kind of time-definitions are supported. And their interactions.
>   Possibles include
>   
>   * absolute time (epoch),
>   * relative to a specific time elsewhere defined in the file.
>   * Relative to boot time of tinman component
>   * relative to CL parameter abs time
>   * relative to approximate switchover to regular block production

This might take some tinkering, but having `gatling` replay 30 days results in 1,464,595 actions (~36,614 blocks on testnet) when I test it.  This is not enough to fully implement the requirements.  I suggest we have `gatling` go back further to make the `backlog.actions` longer, perhaps a year.  Problem is, it takes a local node about 9 hours to reply 30 days of mainnet actions, only resulting in ~1 day of testnet actions.

One solution is to provide `metadata["backfill:transactions_per_block"]` in `backfill.actions`.

Another solution is just to change `metadata["recommended:miss_blocks"]` by subtracting ~864,000 blocks.  The trouble with that *at the moment* is that it will not miss enough blocks to activate HF20.  This might be ok because by the time the testnet is fully bootstrapped, there are enough actions to activate HF20.  Needs testing.

> * [ ]  define which actions are supported, and any unique parameters they may have. Must support witness price-feed publishing

See: https://github.com/steemit/tinman/issues/143#issuecomment-429208721.  However, price-feed publishing cannot be supported in the backfill unless they are published from `initminer` (these would have to be injected into the backfill because `initminer` never publishes price feeds on mainnet).  I believe the problem I was having with simply publishing a price feed after bootstrap was due using mainnet prefix.  We can fix this by using `prefixsub` on the normal `gatling` phase.

**Comment by inertia186** [comment]
Just to clarify, I think *some* `durables` can be part of the bootstrap.  And some can be later on.

**Comment by relativityboy** [comment]
OK,
