### ISSUE TITLE
TN: Add support for price-feeds in bootstrap initial state.

### ISSUE THREAD

**Issue by relativityboy** [steemit/tinman#156]
As a testnet I need to have valid price-feed information from the moment I start producing blocks, *so that my developers can accurately test me, and their client applications*.

*Note: **Price feed information does not need to be streamed, nor does it need to come from main-net. Those behaviors are out of the scope of this story**.*

#155 needs to be completed 1st.

**AC**
- [ ] valid, configurable price-feed information is stored in a configuration/bootstrapping file and is set 'by default' (configuration file is part of example testnet launch process)
- [ ] the above is tested for functionality testing mechanism is described in `# Result`

**Comment by inertia186** [comment]
It is my understanding that we need 7 witnesses to give a price feed in order for it to make any difference.  We can only get `initminer` to create price feeds in fastgen.  So I don't think we can do this in the bootstrap.

**Comment by relativityboy** [comment]
I'd thought a single witness price declaration was enough. @mvandeberg?

But if you're right @inertia186, the following is a speculative approach, not advocacy:
1. Provide a set of 'pricefeed' witness keys to bootstrap
1. Vote in the witnesses
1. Change their keys to the pricefeed keys
1. update price feed
1. change the keys to the keys on witness0

**Comment by mvandeberg** [comment]
@relativityboy's process for setting a witness price feed is correct, but @inertia186 is also correct that we need 7 witnesses to give a price feed for it to be accepted.

There is also a maximum age limit on price feeds. If needed, that is something that could be changed for work better on testnet for tinman. Once the current price feed is set, it won't be unset. The median feed only advances if there are the minimum 7 recent feeds.

**Comment by inertia186** [comment]
Since we need 7 witnesses and only (hopefully someday) only need to express it once, I added feeds to durables that will load just before gatling.  See: https://github.com/steemit/steem-deployments/pull/28/commits/0938cd8795451a45e04be772e0c67709edf31b88
