### ISSUE TITLE
TN: "Create an account" service via RPC/Web - post bootstrap

### ISSUE THREAD

**Issue by relativityboy** [steemit/tinman#167]
As a developer I want to be able to create my own accounts on the testnet that have sufficient bandwidth to post and do transactions, at will, at no cost, and with minimal foreknowledge, so that I can develop apps on the testnet in the way that best suits my company's development cycle. So that barriers to using Steem are lowered.

**AC**
- [ ] endpoint that supports creating an account (only account name 
- [ ] small splash page with current block number and input fields for creating an account
- [ ] pub & prive key can be auto-generated on splash page
- [ ] add jussi routing as needed

**Comment by inertia186** [comment]
Suggestion: the web page should check if the account exists and if it does, let them log into the testnet condenser, maybe hinting that they should use their mainnet keys.

**Comment by inertia186** [comment]
Well, I got stuck in package managemenet hell (failed: `pipenv install Flask='0.11.*'1`), but this got met unstuck: https://github.com/pypa/pipenv/issues/2871

**Comment by relativityboy** [comment]
> Suggestion: the web page should check if the account exists and if it does, let them log into the testnet condenser, maybe hinting that they should use their mainnet keys.

Yes. Many, many improvements. Other issues.

**Comment by inertia186** [comment]
### Quickstart:

```bash
git pull
pip install .
copy server.conf.example server.conf
tinman server \
    --get-dev-key path/to/get_dev_key \
    --signer path/to/sign_transaction \
    --timeout 600 \
    --chain-id=46d82ab7d8db682eb1959aed0ada039a6d49afa1602491f93dde9cac3e8e6c32
```
