### ISSUE TITLE
TN: Tinman: Support not running stages of tn lifecycle

### ISSUE THREAD

**Issue by relativityboy** [steemit/tinman#176]
Just make sure tinman supports the various stages.

**AC**

- [x] make sure `no-main-accounts` fix works
- [x] gigantor can use the fix: https://github.com/steemit/gigantor/pull/12
- [x] deployments can use the output of gigantor: https://github.com/steemit/steem-deployments/pull/38

**Edit:** by @inertia186, added requirements and **AC**

**Comment by inertia186** [comment]
Critical stages verified on sandbox.
