### ISSUE TITLE
Test Net Triggered Hardfork

### ISSUE THREAD

**Issue by mvandeberg** [steemit/tinman#21]
For hardfork releases, it is important to test the moment of the hardfork on the test net.

Witnesses automatically vote for new hardforks they are aware of as soon as they produce a block. We need to prevent that behavior (or prevent the hardfork) on the test net and give Steemit a way to trigger a hardfork when we want to.

While I am not a fan of doing this for unit tests, we could create a testnet op that needs to be signed by initminer that triggers a hardfork. So long as the hardfork date witnesses vote for is in the future (it should be) then the only change we need to make is the addition of this operation.

**Comment by relativityboy** [comment]
@mvandeberg - with our current setup of the testnet, I'm inclined to close this. Objections? 👍 👎
