### ISSUE TITLE
Create tinman script to automate transition of block production

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/tinman#57]
As a developer, or an automatic process, I want to be able to call a single function and have it make a node, `Seed` on a Testnet become a valid Witness so that my Testnet can transition from Bootstrap to normal block production.

**AC**
- [ ] create a function that accepts a url to `Seed`, a block-number/block-id for `endblock` and a set of witness keys `keys`
- [ ] the function does an RPC call to `Seed` to determine whether the remote node has caught up to`endblock` if not, it sleeps and repeats otherwise
- [x] Outputs a single transaction signed by all witnesses, using `keys` to alter their block production keys.
- [ ] optionally - make `Seed` into a witness node (give it a top 20 name and signing priv key)
- [ ] returns `0` on completion, `1` on error or timeout, with logging

---
### Original description:

- Use RPC query to determine whether the remote node has caught up to realtime
- If it has not, or if the last block is not empty, then sleep (5 seconds or so?) and repeat the RPC query
- Output a single transaction signed by all witnesses to alter their block production keys

**Comment by relativityboy** [comment]
Points will be "rough" there is some code around this but there are big unknowns.

**Comment by relativityboy** [comment]
IIRC pointing, we thought @inertia186's comment above may be inaccurate.

**Comment by relativityboy** [comment]
We did the handoff work as per #76 and it was... not entirely successful.

The process that worked was to 
1. update the keys for, and vote in `Seed`'s witnesses 
1. tell `Bootstrap` to produce enough empty blocks to clear the current witness round.

This got `Seed` to begin producing blocks regularly.
