### ISSUE TITLE
TN: Choose client library

### ISSUE THREAD

**Issue by relativityboy** [steemit/tinman#62]
As a tinman developer, I want to offload as much logic as possible to a well performing, maintained, client library.

This involves an evaluation of all possible libraries, and a description of what would/will be required to bring the chosen library "up to snuff".

**AC**
- [x] choose client library and put that choice, and justification in a comment titled `# Results`
- [x] in `# Results` describe the changes necessary to tinman in a section `### tinman updates`.
- [x] in `# Results` describe the changes necessary to the chosen library in a section `### library updates`, and a list of stories (actual story numbers).

**Comment by feruzm** [comment]
## beem

beem seem to have some improvements over `steem-python`

```
from beem import Steem
stm = Steem(node=[“https://api.steemit.com“, “wss://testnet.steem.vc”])
stm.prefix
```
>‘STM’
```
stm.rpc.next()
stm.prefix
```
>‘STX’


At first beem is connected to “https://api.steemit.com/”
`stm.rpc.next()` switches over to the next url, the chain is automatically adjusted

**Comment by relativityboy** [comment]
Based on @feruzm's [comment](https://github.com/steemit/simple_steem_client/issues/22#issuecomment-407401439) and `beems` hard configuration approach, [simple-steem](https://github.com/steemit/simple_steem_client) looks like a very strong contender.

**Comment by feruzm** [comment]
# Results

Thank you @relativityboy, yes as mentioned... simple-steem-client library does the job well in its current state because there is really only few rpc calls to take a snapshot and test.

@inertia186 did some changes yesterday on tinman, further changes specific to custom testnet could be configured through tinman.
