### ISSUE TITLE
TN: Conduct an analysis of start_time computation and --realtime flag

### ISSUE THREAD

**Issue by relativityboy** [steemit/tinman#80]
There have been instances in testnet production when 
* the `wait blocks` operation over-runs the present moment
* the `--realtime` flag doesn't slowdown empty block production at the present moment but over-runs it very quickly (going through 2M blocks in an hour)
* when choosing a seemingly reasonable start_time causes the testnet to run out of blocks "well in the past"

Relates to steemit/steem#2801

**AC**
- [x] do an analysis of the code with the above issues in mind, and put the findings in a comment titled `# Results`

**Comment by inertia186** [comment]
The goal is to make `start_time` less fiddly, but it appears we are trying to fix the related `wait_block` / `--realtime` logic without even getting it deployed (rather, it should work but it isn't, we just need to troubleshoot it).  Or we're saying that this logic is delaying / complicating deployment.

An alternative might be to do an automatic analysis on the original `snapshot.json`, measure the number of `account_create`, double that number (`account_update`), add 30 witnesses, divide by the number of transactions.  That's the number of blocks needed.  Then determine an appropriate `start_time`.

We use `start_time` to instruct `submit` when to (blindly) begin 3-second block times.  In the process, we get instructions about block arragngement from `txgen`, which seems like a bad place for that logic to live.

##### What I don't buy:
* I have never observed `--realtime` doing a significant overrun.  If this is meant to fix that behavior, I have yet to personally observe it.  Certain orchestrations may have.
* I don't like the idea of dropping true pipes.  We already have enough headaches with `snapshot.json` not being pipe-enabled.  If #77 hadn't worked out, my Plan B would have been to rework `snapshot.json` into a pipe-enabled structure.  In fact, it might not be a bad idea to revisit later on, if we ever wanted to drop `ijson` as a dependency.
* Adopting a fake pipe (i.e. using time travel to move the transaction count from the bottom of the pipe to the top) seems dubious.

##### What I sorta don't buy:
* I get that guessing `start_time` is bad.  Today, guessing 48 hours should work, but in a year, it might really need 72 hours, when it slows down block production while it's still updateing accounts.  We won't know the guess is wrong until devops says "Hey, testnet never finishes initializing" and we have to go troubleshooting.  I wonder if on the one hand guessing `start_time` is a bandaid, but on the other hand, correctly computing it to within 15 minutes just kicks the can down the road for orchestration.

##### What I do buy:
* The notion that `txgen` should only generate transactions.  I get that.  I think it should not convey block arrangement.
* I guess to put it another way, I like the idea of `txgen` **only** spitting out transactions and letting its upstream decide what to do with them.
* More specifically, I don't like using `wait_blocks` to communicate.  Currently, we use `wait_blocks` to communicate that **a)** we have reached *n* transactions and need a new block and **b)** we're done with all transactions so here are some empty blocks until you're ready to had off to Seed.

**Comment by relativityboy** [comment]
What headaches did we have with 'snapshot.json' not being pipe enabled?

**Comment by inertia186** [comment]
# Result

I think the root cause of block overrun was a faulty configuration in orchestration that has been corrected.  Now that `start_time` is automatically computed, we no longer need to worry about the situation 1 year from now where the hard-coded `start_time` causes problems due to the number of accounts increasing in that time.  I believe we can close this issue.

If we want to revisit `txgen` block formation, we can open a new issue.

**Comment by relativityboy** [comment]
IMO the txgen solution is stopgap as both `txgen.py` and `submit.py` can be run independently, and the situation where start_time actually matters is in submit.py. This could result in a txgen.list file with an incorrect number of 'miss_blocks'.

It has done a good job as we're using it today, and has helped us keep the code rolling. 

I'm in favor of closing this issue and opening another one to create a more permanent solution.
